//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyforJob
    {
        public int ApplierId { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public string uploadfile { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<int> ProfileId { get; set; }
    
        public virtual JobDetails JobDetails { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
