//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDetails
    {
        public JobDetails()
        {
            this.ApplyforJob = new HashSet<ApplyforJob>();
        }
    
        public int JobId { get; set; }
        public string JobTitle { get; set; }
        public string JobContent { get; set; }
        public string JobImage { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public Nullable<int> BrowseId { get; set; }
        public string JobType { get; set; }
        public string Languages { get; set; }
        public string Salary { get; set; }
        public string Vacancies { get; set; }
        public string EducationLevel { get; set; }
        public string JobRequirements { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DateJob { get; set; }
    
        public virtual ICollection<ApplyforJob> ApplyforJob { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
